version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${RAILWAY_STATIC_URL:-http://localhost:8000}
    depends_on:
      - backend
    restart: always 